---
Name: FsxLustre-Persistent
StorageType: FsxLustre
MountDir: /sbo/data
FsxLustreSettings:
  DeploymentType: PERSISTENT_2
  StorageCapacity: 1200  # Setup Lustre FSx for 1.2TiB (minimum allowed)
  PerUnitStorageThroughput: 250  # Request a bandwidth of 250Mbps/TiB (similar to SCRATCH_2)
  DataCompressionType: LZ4  # Data compression for higher-throughput between OSSs <-> OSTs
  DataRepositoryAssociations:
    - Name: Nexus-DRA
      BatchImportMetaDataOnCreate: true
      DataRepositoryPath: s3://sbonexusdata
      FileSystemPath: /project
      AutoExportPolicy: [NEW]
      AutoImportPolicy: [NEW, CHANGED, DELETED]
    - Name: Containers-DRA
      BatchImportMetaDataOnCreate: true
      DataRepositoryPath: s3://sboinfrastructureassets/containers
      FileSystemPath: /containers
      AutoExportPolicy: [NEW]
      AutoImportPolicy: [NEW, CHANGED, DELETED]
    - Name: Scratch-DRA
      BatchImportMetaDataOnCreate: true
      DataRepositoryPath: s3://sbo-scatch-wu9hk9
      FileSystemPath: /scratch
      AutoExportPolicy: [NEW, CHANGED, DELETED]
      AutoImportPolicy: [NEW, CHANGED, DELETED]
